# Server Configuration
name = "production-api"
version = "1.2.3"
debug = false
port = 8080
host = "0.0.0.0"

# Database configuration  
[database]
type = "postgresql"
host = "db.example.com"
port = 5432
database = "app_production"
username = "app_user"
pool_size = 20
ssl_mode = "require"
timeout = 30

# Redis configuration
[redis]
host = "redis.example.com"
port = 6379
database = 0
password = "redis_secret"
max_connections = 100

# Logging configuration
[logging]
level = "info"
format = "json"
file = "/var/log/app/server.log"
max_size_mb = 100
max_files = 5
compress = true

# Authentication settings
[auth]
secret_key = "your-secret-key-here"
token_expiry_hours = 24
refresh_token_expiry_days = 30
bcrypt_rounds = 12

# Feature flags
[features]
enable_analytics = true
enable_caching = true
enable_rate_limiting = true
maintenance_mode = false

# External services
[services]
stripe_api_key = "sk_live_..."
sendgrid_api_key = "SG...."
aws_region = "us-west-2"